apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-flask-app
  labels:
    app: blue-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-flask-app
  template:
    metadata:
      labels:
        app: blue-flask-app
    spec:
      containers:
      - name: blue-flask-app
        image: goldin2008/blue-flask-app
        ports:
        - containerPort: 5000