apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-flask-app
  labels:
    app: green-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green-flask-app
  template:
    metadata:
      labels:
        app: green-flask-app
    spec:
      containers:
      - name: flask-app
        image: goldin2008/green-flask-app
        ports:
        - containerPort: 5000